### ISSUE TITLE
Unbalanced Visibility and Size of UI at Signin/Login Page

### ISSUE THREAD

**Issue by karan-joshi-1** [upstash/upstash-web#190]
<img width="1512" alt="Screenshot 2024-02-08 at 9 37 52 PM" src="https://github.com/upstash/upstash-web/assets/128008084/199381c8-2c7e-4abb-be13-3dc2c10fde63">

1- The contrast between the text and the background is not sufficient, especially on the left-hand side and also there is a huge contrast gap between the left and right sides.

2- There is no error state and validation functionality or inline validation for the form fields, which is important for a good user experience.

3-The links for  "Create an account"  should be prominently displayed.

**Comment by karan-joshi-1** [comment]
@enesakar what do you think about any of these?

**Comment by ytkimirti** [comment]
Thanks for your feedback on the design, we will discuss this with our designer.

About the inline errors or validation, are they not showing up to you when you try to log in?

**Comment by karan-joshi-1** [comment]
> Thanks for your feedback on the design, we will discuss this with our designer.
> 
> About the inline errors or validation, are they not showing up to you when you try to log in?

no, they are not i tried this on both the login and sign-in pages, and there are no validation checks.

**Comment by ytkimirti** [comment]
Yeah we added that so it wouldn't disturb you when typing. It updates in realtime after the first error.

**Comment by karan-joshi-1** [comment]
@ytkimirti  Thanks for letting me know. Its a unique system that you have implemented.
